version: '3.8'

services:
  web:
    build:
      target: deps
    command: npm run dev
    volumes:
      - ..:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
